-- Para borrar el procedure
--DROP PROCEDURE MAILN0
--GO


CREATE PROCEDURE MAILN0
	
	/*Si quiere probarlo  las variables cambienlas por estas
	Declare @CORREO_USUARIO varchar(50)
	Declare @NOMBRE_USUARIO varchar(50)
	Declare @NOMBRE_CAMBIO varchar(50)
	Declare @CAMBIO_ID int
	Declare @FECHA_ASIGNACION date
	
	*/
	-------------------
	@CORREO_USUARIO varchar(50),
	@NOMBRE_USUARIO varchar(50),
	@NOMBRE_CAMBIO varchar(50),
	@CAMBIO_ID int,
	@FECHA_ASIGNACION date
	AS --El AS se va, se va la declaracion del procedure y se va el go al final del procedure
	------
	
	Declare cSource CURSOR For
	SELECT USUARIO.CORREO_USUARIO, USUARIO.NOMBRE_USUARIO, CAMBIO.NOMBRE_CAMBIO, 
		CAMBIO.CAMBIO_ID, NIVEL0.FECHA_ASIGNACION FROM NIVEL0, AREA, DEPARTAMENTO, 
		USUARIO, CAMBIO WHERE NIVEL0.CAMBIO_ID = CAMBIO.CAMBIO_ID AND NIVEL0.AREA_ID = AREA.AREA_ID 
		AND AREA.DEPTO_ID = DEPARTAMENTO.DEPTO_ID AND 
		DEPARTAMENTO.RESPONSABLE_ID = USUARIO.USUARIO_ID AND NIVEL0.STATUS LIKE ('Pendiente');
                 
    Open cSource
    FETCH NEXT from cSource into @CORREO_USUARIO, @NOMBRE_USUARIO, @NOMBRE_CAMBIO, @CAMBIO_ID, @FECHA_ASIGNACION
    
    While (@@FETCH_STATUS=0)
    BEGIN
	/*	exec @rc = master.dbo.xp_smtp_sendmail
	  @FROM             = N'proficy@talisman.internal.pg.com',
      @FROM_NAME		= 'Control de Cambios',
      @TO               = @CORREO_USUARIO,
      @subject          = 'Control de Cambios',
      @message          = CONCAT('Un nuevo cambio llamado ', @NOMBRE_CAMBIO) + ' \n se encuentra en espera para su aprobacion, favor de entrar al sistema de cambios. \n Atte. Servicio de Sistemas de Cambios'
      @type             = N'text/html'
      @server           = N'smtpgw.pg.com'

		select RC = @rc
		
	*/
		--PRINT @CORREO_USUARIO 
		--PRINT @CAMBIO_ID 
		--PRINT @FECHA_ASIGNACION
		FETCH NEXT from cSource into @CORREO_USUARIO, @NOMBRE_USUARIO, @NOMBRE_CAMBIO, @CAMBIO_ID, @FECHA_ASIGNACION
    END
    Close cSource
	Deallocate cSource
GO

CREATE PROCEDURE MAILN1QA
	
	@CORREO_USUARIO varchar(50),
	@NOMBRE_USUARIO varchar(50),
	@NOMBRE_CAMBIO varchar(50),
	@CAMBIO_ID int,
	@FECHA_ASIGNACION date
	AS
	
	Declare cSource CURSOR For
	SELECT USUARIO.CORREO_USUARIO, USUARIO.NOMBRE_USUARIO, CAMBIO.NOMBRE_CAMBIO, 
		CAMBIO.CAMBIO_ID, NIVEL1_QA.FECHA_ASIGNACION FROM NIVEL1_QA, AREA, DEPARTAMENTO,
		USUARIO, CAMBIO WHERE NIVEL1_QA.CAMBIO_ID = CAMBIO.CAMBIO_ID AND 
		AREA.NOMBRE_AREA LIKE 'QA' AND AREA.DEPTO_ID = DEPARTAMENTO.DEPTO_ID AND 
		DEPARTAMENTO.RESPONSABLE_ID = USUARIO.USUARIO_ID AND NIVEL1_QA.STATUS 
		LIKE ('Pendiente') AND (NIVEL1_QA.N1QA_ACEPTADO = '1');
                 
    Open cSource
    FETCH NEXT from cSource into @CORREO_USUARIO, @NOMBRE_USUARIO, @NOMBRE_CAMBIO, @CAMBIO_ID, @FECHA_ASIGNACION
    
    While (@@FETCH_STATUS=0)
    BEGIN
		-- Metodo magico de correos
		FETCH NEXT from cSource into @CORREO_USUARIO, @NOMBRE_USUARIO, @NOMBRE_CAMBIO, @CAMBIO_ID, @FECHA_ASIGNACION
    END
    Close cSource
	Deallocate cSource
GO

CREATE PROCEDURE MAILN1HSE
	
	@CORREO_USUARIO varchar(50),
	@NOMBRE_USUARIO varchar(50),
	@NOMBRE_CAMBIO varchar(50),
	@CAMBIO_ID int,
	@FECHA_ASIGNACION date
	AS
	
	Declare cSource CURSOR For
	SELECT USUARIO.CORREO_USUARIO, USUARIO.NOMBRE_USUARIO, CAMBIO.NOMBRE_CAMBIO, CAMBIO.CAMBIO_ID, 
		NIVEL1_HSE.FECHA_ASIGNACION FROM NIVEL1_HSE, AREA, DEPARTAMENTO, USUARIO, CAMBIO 
		WHERE NIVEL1_HSE.CAMBIO_ID = CAMBIO.CAMBIO_ID AND 
		AREA.NOMBRE_AREA LIKE 'HSE' AND AREA.DEPTO_ID = DEPARTAMENTO.DEPTO_ID AND 
		DEPARTAMENTO.RESPONSABLE_ID = USUARIO.USUARIO_ID AND NIVEL1_HSE.STATUS LIKE ('Pendiente') 
		AND (NIVEL1_HSE.N1HSE_ACEPTADO = '1');
                 
    Open cSource
    FETCH NEXT from cSource into @CORREO_USUARIO, @NOMBRE_USUARIO, @NOMBRE_CAMBIO, @CAMBIO_ID, @FECHA_ASIGNACION
    
    While (@@FETCH_STATUS=0)
    BEGIN
		-- Metodo magico de correos
		FETCH NEXT from cSource into @CORREO_USUARIO, @NOMBRE_USUARIO, @NOMBRE_CAMBIO, @CAMBIO_ID, @FECHA_ASIGNACION
    END
    Close cSource
	Deallocate cSource
GO

CREATE PROCEDURE MAILN2
	
	@CORREO_USUARIO varchar(50),
	@NOMBRE_USUARIO varchar(50),
	@NOMBRE_CAMBIO varchar(50),
	@CAMBIO_ID int,
	@FECHA_ASIGNACION date
	AS
	
	Declare cSource CURSOR For
	SELECT USUARIO.CORREO_USUARIO, USUARIO.NOMBRE_USUARIO, CAMBIO.NOMBRE_CAMBIO, 
		CAMBIO.CAMBIO_ID, NIVEL2.FECHA_ASIGNACION FROM NIVEL2, CAMBIO, AREAS_SOPORTE, 
		USUARIO WHERE NIVEL2.CAMBIO_ID = CAMBIO.CAMBIO_ID AND 
		AREAS_SOPORTE.AREA_SOPORTE_ID = NIVEL2.AREA_SOPORTE_ID 
		AND AREAS_SOPORTE.REPONSABLE_ID = USUARIO.USUARIO_ID 
		AND NIVEL2.STATUS LIKE ('Pendiente');
                 
    Open cSource
    FETCH NEXT from cSource into @CORREO_USUARIO, @NOMBRE_USUARIO, @NOMBRE_CAMBIO, @CAMBIO_ID, @FECHA_ASIGNACION
    
    While (@@FETCH_STATUS=0)
    BEGIN
		-- Metodo magico de correos
		FETCH NEXT from cSource into @CORREO_USUARIO, @NOMBRE_USUARIO, @NOMBRE_CAMBIO, @CAMBIO_ID, @FECHA_ASIGNACION
    END
    Close cSource
	Deallocate cSource
GO

CREATE PROCEDURE MAILN1BACK
	
	@CORREO_USUARIO varchar(50),
	@NOMBRE_USUARIO varchar(50),
	@NOMBRE_CAMBIO varchar(50),
	@CAMBIO_ID int,
	@FECHA_ASIGNACION date
	AS
	
	Declare cSource CURSOR For
		SELECT USUARIO.CORREO_USUARIO, USUARIO.NOMBRE_USUARIO, CAMBIO.NOMBRE_CAMBIO, CAMBIO.CAMBIO_ID, 
			NIVEL0.FECHA_ASIGNACION FROM NIVEL0, AREA, DEPARTAMENTO, USUARIO, CAMBIO 
			WHERE NIVEL0.CAMBIO_ID = CAMBIO.CAMBIO_ID AND NIVEL0.AREA_ID = AREA.AREA_ID 
			AND AREA.DEPTO_ID = DEPARTAMENTO.DEPTO_ID AND DEPARTAMENTO.BACKUP_ID = USUARIO.USUARIO_ID 
			AND NIVEL0.STATUS LIKE ('Pendiente');
                 
    Open cSource
    FETCH NEXT from cSource into @CORREO_USUARIO, @NOMBRE_USUARIO, @NOMBRE_CAMBIO, @CAMBIO_ID, @FECHA_ASIGNACION
    
    While (@@FETCH_STATUS=0)
    BEGIN
		-- Metodo magico de correos
		PRINT  @CORREO_USUARIO
		PRINT  @FECHA_ASIGNACION
		Declare @FECHA_CUR date = @FECHA_ASIGNACION
		Declare @Count int = 0
		
		WHILE (@FECHA_CUR <= GETDATE())
		BEGIN
			--PRINT 'HOLA'
			--PRINT DATEPART(weekday, GETDATE())
			--PRINT @FECHA_CUR
			
			IF(NOT(DATEPART(weekday, GETDATE()) = 1 OR DATEPART(weekday, GETDATE()) = 7))
			BEGIN
				SET @Count = @Count + 1
			END
			
			SET @FECHA_CUR = DATEADD(day, 1, @FECHA_CUR)
			
		END
		
		IF (@Count > 2)
		BEGIN
			---Manda correo magicamente
			PRINT @Count
		END
		
		SET @Count = 0
		FETCH NEXT from cSource into @CORREO_USUARIO, @NOMBRE_USUARIO, @NOMBRE_CAMBIO, @CAMBIO_ID, @FECHA_ASIGNACION
    END
    Close cSource
	Deallocate cSource
	
GO


CREATE PROCEDURE MAILN1QABACK
	
	@NIVEL_ID int,
	@CORREO_USUARIO varchar(50),
	@NOMBRE_USUARIO varchar(50),
	@NOMBRE_CAMBIO varchar(50),
	@CAMBIO_ID int,
	@FECHA_ASIGNACION date
	AS
	
	Declare cSource CURSOR For
		SELECT DISTINCT (NIVEL1_QA.NIVEL1_QA_ID), USUARIO.CORREO_USUARIO, USUARIO.NOMBRE_USUARIO, 
			CAMBIO.NOMBRE_CAMBIO, CAMBIO.CAMBIO_ID, NIVEL1_QA.FECHA_ASIGNACION 
			FROM NIVEL1_QA, USUARIO, CAMBIO WHERE NIVEL1_QA.CAMBIO_ID = CAMBIO.CAMBIO_ID AND 
			NIVEL1_QA.STATUS = 'Pendiente' AND NIVEL1_QA.N1QA_ACEPTADO = '1' 
			AND USUARIO.PERFIL_USUARIO LIKE 'n1qa' AND USUARIO.PRINCIPAL = '0';
                 
    Open cSource
    FETCH NEXT from cSource into @NIVEL_ID, @CORREO_USUARIO, @NOMBRE_USUARIO, @NOMBRE_CAMBIO, @CAMBIO_ID, @FECHA_ASIGNACION
    
    While (@@FETCH_STATUS=0)
    BEGIN
		-- Metodo magico de correos
		PRINT  @CORREO_USUARIO
		PRINT  @FECHA_ASIGNACION
		Declare @FECHA_CUR date = @FECHA_ASIGNACION
		Declare @Count int = 0
		
		WHILE (@FECHA_CUR <= GETDATE())
		BEGIN
			--PRINT 'HOLA'
			--PRINT DATEPART(weekday, GETDATE())
			--PRINT @FECHA_CUR
			
			IF(NOT(DATEPART(weekday, GETDATE()) = 1 OR DATEPART(weekday, GETDATE()) = 7))
			BEGIN
				SET @Count = @Count + 1
			END
			
			SET @FECHA_CUR = DATEADD(day, 1, @FECHA_CUR)
			
		END
		
		IF (@Count > 2)
		BEGIN
			---Manda correo magicamente
			PRINT @Count
		END
		
		SET @Count = 0
		FETCH NEXT from cSource into @NIVEL_ID, @CORREO_USUARIO, @NOMBRE_USUARIO, @NOMBRE_CAMBIO, @CAMBIO_ID, @FECHA_ASIGNACION
    END
    Close cSource
	Deallocate cSource
	
GO


CREATE PROCEDURE MAILN1HSEBACK
	
	@NILVER_ID int,
	@CORREO_USUARIO varchar(50),
	@NOMBRE_USUARIO varchar(50),
	@NOMBRE_CAMBIO varchar(50),
	@CAMBIO_ID int,
	@FECHA_ASIGNACION date
	AS
	
	Declare cSource CURSOR For
		SELECT DISTINCT (NIVEL1_HSE.NIVEL1_HSE_ID), USUARIO.CORREO_USUARIO, USUARIO.NOMBRE_USUARIO, 
			CAMBIO.NOMBRE_CAMBIO, CAMBIO.CAMBIO_ID, NIVEL1_HSE.FECHA_ASIGNACION 
			FROM NIVEL1_HSE, USUARIO, CAMBIO WHERE NIVEL1_HSE.CAMBIO_ID = CAMBIO.CAMBIO_ID AND 
			NIVEL1_HSE.STATUS = 'Pendiente' AND NIVEL1_HSE.N1HSE_ACEPTADO = '1' 
			AND USUARIO.PERFIL_USUARIO LIKE 'n1hse' AND USUARIO.PRINCIPAL = '0';
                 
    Open cSource
    FETCH NEXT from cSource into @NIVEL_ID, @CORREO_USUARIO, @NOMBRE_USUARIO, @NOMBRE_CAMBIO, @CAMBIO_ID, @FECHA_ASIGNACION
    
    While (@@FETCH_STATUS=0)
    BEGIN
		-- Metodo magico de correos
		PRINT  @CORREO_USUARIO
		PRINT  @FECHA_ASIGNACION
		Declare @FECHA_CUR date = @FECHA_ASIGNACION
		Declare @Count int = 0
		
		WHILE (@FECHA_CUR <= GETDATE())
		BEGIN
			--PRINT 'HOLA'
			--PRINT DATEPART(weekday, GETDATE())
			--PRINT @FECHA_CUR
			
			IF(NOT(DATEPART(weekday, GETDATE()) = 1 OR DATEPART(weekday, GETDATE()) = 7))
			BEGIN
				SET @Count = @Count + 1
			END
			
			SET @FECHA_CUR = DATEADD(day, 1, @FECHA_CUR)
			
		END
		
		IF (@Count > 2)
		BEGIN
			---Manda correo magicamente
			PRINT @Count
		END
		
		SET @Count = 0
		FETCH NEXT from cSource into @NIVEL_ID, @CORREO_USUARIO, @NOMBRE_USUARIO, @NOMBRE_CAMBIO, @CAMBIO_ID, @FECHA_ASIGNACION
    END
    Close cSource
	Deallocate cSource
	
GO


CREATE PROCEDURE MAILN2BACK
	
	@CORREO_USUARIO varchar(50),
	@NOMBRE_USUARIO varchar(50),
	@NOMBRE_CAMBIO varchar(50),
	@CAMBIO_ID int,
	@FECHA_ASIGNACION date
	AS
	
	Declare cSource CURSOR For
		SELECT USUARIO.CORREO_USUARIO, USUARIO.NOMBRE_USUARIO, CAMBIO.NOMBRE_CAMBIO, CAMBIO.CAMBIO_ID, 
			NIVEL2.FECHA_ASIGNACION FROM NIVEL2, CAMBIO, AREAS_SOPORTE, USUARIO WHERE 
			NIVEL2.CAMBIO_ID = CAMBIO.CAMBIO_ID AND AREAS_SOPORTE.AREA_SOPORTE_ID = NIVEL2.AREA_SOPORTE_ID
			AND AREAS_SOPORTE.BACKUP_ID = USUARIO.USUARIO_ID AND NIVEL2.STATUS LIKE ('Pendiente');
                 
    Open cSource
    FETCH NEXT from cSource into @CORREO_USUARIO, @NOMBRE_USUARIO, @NOMBRE_CAMBIO, @CAMBIO_ID, @FECHA_ASIGNACION
    
    While (@@FETCH_STATUS=0)
    BEGIN
		-- Metodo magico de correos
		PRINT  @CORREO_USUARIO
		PRINT  @FECHA_ASIGNACION
		Declare @FECHA_CUR date = @FECHA_ASIGNACION
		Declare @Count int = 0
		
		WHILE (@FECHA_CUR <= GETDATE())
		BEGIN
			--PRINT 'HOLA'
			--PRINT DATEPART(weekday, GETDATE())
			--PRINT @FECHA_CUR
			
			IF(NOT(DATEPART(weekday, GETDATE()) = 1 OR DATEPART(weekday, GETDATE()) = 7))
			BEGIN
				SET @Count = @Count + 1
			END
			
			SET @FECHA_CUR = DATEADD(day, 1, @FECHA_CUR)
			
		END
		
		IF (@Count > 2)
		BEGIN
			---Manda correo magicamente
			PRINT @Count
		END
		
		SET @Count = 0
		FETCH NEXT from cSource into @CORREO_USUARIO, @NOMBRE_USUARIO, @NOMBRE_CAMBIO, @CAMBIO_ID, @FECHA_ASIGNACION
    END
    Close cSource
	Deallocate cSource
	
GO