
CREATE TABLE #NIVELES(
	CORREO_USUARIO VARCHAR(50),
	NOMBRE_USUARIO VARCHAR(50),
	NOMBRE_CAMBIO VARCHAR(50),
	CAMBIO_ID INT,
	FECHA_ASIGNACION DATETIME,
	PRINCIPAL BIT
)

INSERT INTO #NIVELES (CORREO_USUARIO, NOMBRE_USUARIO, NOMBRE_CAMBIO, CAMBIO_ID, FECHA_ASIGNACION, PRINCIPAL) 
		SELECT USUARIO.CORREO_USUARIO, USUARIO.NOMBRE_USUARIO, CAMBIO.NOMBRE_CAMBIO, 
		CAMBIO.CAMBIO_ID, NIVEL0.FECHA_ASIGNACION, USUARIO.PRINCIPAL FROM NIVEL0, AREA, DEPARTAMENTO, 
		USUARIO, CAMBIO WHERE NIVEL0.CAMBIO_ID = CAMBIO.CAMBIO_ID AND NIVEL0.AREA_ID = AREA.AREA_ID 
		AND AREA.DEPTO_ID = DEPARTAMENTO.DEPTO_ID AND 
		DEPARTAMENTO.RESPONSABLE_ID = USUARIO.USUARIO_ID AND NIVEL0.STATUS LIKE ('Pendiente')
		
		UNION ALL
		SELECT USUARIO.CORREO_USUARIO, USUARIO.NOMBRE_USUARIO, CAMBIO.NOMBRE_CAMBIO, 
		CAMBIO.CAMBIO_ID, NIVEL1_QA.FECHA_ASIGNACION, USUARIO.PRINCIPAL FROM NIVEL1_QA, 
		USUARIO, CAMBIO WHERE NIVEL1_QA.CAMBIO_ID = CAMBIO.CAMBIO_ID
		AND USUARIO.PERFIL_USUARIO LIKE ('n1qa') AND USUARIO.PRINCIPAL = 1
		AND NIVEL1_QA.STATUS 
		LIKE ('Pendiente') AND (NIVEL1_QA.N1QA_ACEPTADO = '1') 
		
		
		UNION ALL
		SELECT USUARIO.CORREO_USUARIO, USUARIO.NOMBRE_USUARIO, CAMBIO.NOMBRE_CAMBIO, CAMBIO.CAMBIO_ID, 
		NIVEL1_HSE.FECHA_ASIGNACION, USUARIO.PRINCIPAL FROM NIVEL1_HSE, USUARIO, CAMBIO 
		WHERE NIVEL1_HSE.CAMBIO_ID = CAMBIO.CAMBIO_ID 
		AND USUARIO.PERFIL_USUARIO LIKE ('n1hse') AND USUARIO.PRINCIPAL = 1 
		AND NIVEL1_HSE.STATUS LIKE ('Pendiente') 
		AND (NIVEL1_HSE.N1HSE_ACEPTADO = '1')
		
		UNION ALL
		SELECT USUARIO.CORREO_USUARIO, USUARIO.NOMBRE_USUARIO, CAMBIO.NOMBRE_CAMBIO, 
		CAMBIO.CAMBIO_ID, NIVEL2.FECHA_ASIGNACION, USUARIO.PRINCIPAL FROM NIVEL2, CAMBIO, AREAS_SOPORTE, 
		USUARIO, NIVEL1_QA, NIVEL1_HSE WHERE NIVEL2.CAMBIO_ID = CAMBIO.CAMBIO_ID AND 
		AREAS_SOPORTE.AREA_SOPORTE_ID = NIVEL2.AREA_SOPORTE_ID 
		AND AREAS_SOPORTE.REPONSABLE_ID = USUARIO.USUARIO_ID 
		AND NIVEL1_QA.CAMBIO_ID = CAMBIO.CAMBIO_ID AND NIVEL1_QA.STATUS = 'Autorizado'
		AND NIVEL1_HSE.CAMBIO_ID = CAMBIO.CAMBIO_ID AND NIVEL1_HSE.STATUS = 'Autorizado'
		AND NIVEL2.STATUS LIKE ('Pendiente')

INSERT INTO #NIVELES(CORREO_USUARIO, NOMBRE_USUARIO, NOMBRE_CAMBIO, CAMBIO_ID, FECHA_ASIGNACION, PRINCIPAL)
		SELECT USUARIO.CORREO_USUARIO, USUARIO.NOMBRE_USUARIO, CAMBIO.NOMBRE_CAMBIO, CAMBIO.CAMBIO_ID, 
		NIVEL0.FECHA_ASIGNACION, USUARIO.PRINCIPAL FROM NIVEL0, AREA, DEPARTAMENTO, USUARIO, CAMBIO 
		WHERE NIVEL0.CAMBIO_ID = CAMBIO.CAMBIO_ID AND NIVEL0.AREA_ID = AREA.AREA_ID 
		AND AREA.DEPTO_ID = DEPARTAMENTO.DEPTO_ID AND DEPARTAMENTO.BACKUP_ID = USUARIO.USUARIO_ID 
		AND NIVEL0.STATUS LIKE ('Pendiente')

		UNION ALL
		SELECT USUARIO.CORREO_USUARIO, USUARIO.NOMBRE_USUARIO, CAMBIO.NOMBRE_CAMBIO, 
		CAMBIO.CAMBIO_ID, NIVEL1_QA.FECHA_ASIGNACION, USUARIO.PRINCIPAL FROM NIVEL1_QA, 
		USUARIO, CAMBIO WHERE NIVEL1_QA.CAMBIO_ID = CAMBIO.CAMBIO_ID
		AND USUARIO.PERFIL_USUARIO LIKE ('n1qa') AND USUARIO.PRINCIPAL = 0
		AND NIVEL1_QA.STATUS 
		LIKE ('Pendiente') AND (NIVEL1_QA.N1QA_ACEPTADO = '1')
			
		UNION ALL
		SELECT USUARIO.CORREO_USUARIO, USUARIO.NOMBRE_USUARIO, CAMBIO.NOMBRE_CAMBIO, CAMBIO.CAMBIO_ID, 
		NIVEL1_HSE.FECHA_ASIGNACION, USUARIO.PRINCIPAL FROM NIVEL1_HSE, USUARIO, CAMBIO 
		WHERE NIVEL1_HSE.CAMBIO_ID = CAMBIO.CAMBIO_ID 
		AND USUARIO.PERFIL_USUARIO LIKE ('n1hse') AND USUARIO.PRINCIPAL = 0 
		AND NIVEL1_HSE.STATUS LIKE ('Pendiente') 
		AND (NIVEL1_HSE.N1HSE_ACEPTADO = '1')
		
		UNION ALL
		SELECT USUARIO.CORREO_USUARIO, USUARIO.NOMBRE_USUARIO, CAMBIO.NOMBRE_CAMBIO, 
		CAMBIO.CAMBIO_ID, NIVEL2.FECHA_ASIGNACION, USUARIO.PRINCIPAL FROM NIVEL2, CAMBIO, AREAS_SOPORTE, 
		USUARIO, NIVEL1_QA, NIVEL1_HSE WHERE NIVEL2.CAMBIO_ID = CAMBIO.CAMBIO_ID AND 
		AREAS_SOPORTE.AREA_SOPORTE_ID = NIVEL2.AREA_SOPORTE_ID 
		AND AREAS_SOPORTE.BACKUP_ID = USUARIO.USUARIO_ID 
		AND NIVEL1_QA.CAMBIO_ID = CAMBIO.CAMBIO_ID AND NIVEL1_QA.STATUS = 'Autorizado'
		AND NIVEL1_HSE.CAMBIO_ID = CAMBIO.CAMBIO_ID AND NIVEL1_HSE.STATUS = 'Autorizado'
		AND NIVEL2.STATUS LIKE ('Pendiente')

	DECLARE @CORREO_USUARIO NVARCHAR(50)
	DECLARE @NOMBRE_USUARIO NVARCHAR(50)
	DECLARE @NOMBRE_CAMBIO NVARCHAR(50)
	DECLARE @CAMBIO_ID INT
	DECLARE @FECHA_ASIGNACION DATETIME 
	DECLARE @PRINCIPAL BIT

DECLARE CSOURCE CURSOR FOR
	SELECT * FROM #NIVELES;
	
OPEN CSOURCE
    FETCH NEXT from CSOURCE INTO @CORREO_USUARIO, @NOMBRE_USUARIO, @NOMBRE_CAMBIO, @CAMBIO_ID, @FECHA_ASIGNACION, @PRINCIPAL
    
    DECLARE @FECHA_CUR DATETIME
    DECLARE @COUNT INT
    
    WHILE (@@FETCH_STATUS=0)
    BEGIN
		-- Metodo magico de correos
		PRINT  @CORREO_USUARIO
		PRINT  @FECHA_ASIGNACION
		SET @FECHA_CUR = @FECHA_ASIGNACION
		SET @COUNT = 0
		
		WHILE (@FECHA_CUR <= GETDATE())
		BEGIN
			
			IF(NOT(DATEPART(weekday, GETDATE()) = 1 OR DATEPART(weekday, GETDATE()) = 7))
			BEGIN
				SET @COUNT = @COUNT + 1
			END
			
			SET @FECHA_CUR = DATEADD(day, 1, @FECHA_CUR)
			
		END
		
		IF (@COUNT > 2 AND @PRINCIPAL = '0')
		BEGIN
			---Manda correo magicamente
			PRINT ('SE LE MANDA CORREO: ' + @CORREO_USUARIO)
			PRINT @COUNT
		END
		
		IF (@COUNT <= 2 AND @PRINCIPAL = '1')
		BEGIN
			---Manda correo magicamente
			PRINT ('SE LE MANDA CORREO: ' + @CORREO_USUARIO)
			PRINT @COUNT
		END
		
		SET @COUNT = 0
		FETCH NEXT FROM CSOURCE INTO @CORREO_USUARIO, @NOMBRE_USUARIO, @NOMBRE_CAMBIO, @CAMBIO_ID, @FECHA_ASIGNACION, @PRINCIPAL
    END
    CLOSE CSOURCE
	DEALLOCATE CSOURCE


DROP TABLE #NIVELES;